# Generated by Django 3.1.7 on 2021-02-27 08:51

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_placeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('position'), nulls_last=True)]},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Позиция'),
        ),
    ]
