# Generated by Django 3.1.7 on 2021-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210304_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
